### ISSUE TITLE
Method <setDocumentDomain(String s)> Not available in aws version 1.9.13

### ISSUE THREAD

**Issue by arvinthdd** [tahseen/amazon-cloudsearch-client-java#2]
In README.md section, The sample code for instantiating client says "client.setSearchDomain(searchEndpoint);" for adding search endpoint string. 

But this method is not available when I download the aws jars using maven dependency mentioned in the bottom (aws-java-sdk version 1.9.13). 
Class : AmazonCloudSearchClient
Method : setSearchDomain( String searchEndpoint) <<<< This method is not available in 1.9.13 and 1.9.16 >>>>

Checked in aws sdk version 1.9.16 version too. In the m2.repository, I checked the sources downloaded by Maven for 1.9.13 (filename: aws-java-sdk-cloudsearch-1.9.13-sources.jar)

**Comment by tahseen** [comment]
That is why I created this library. The Official Amazon AWS SDK does not have these functionality.

**Comment by tahseen** [comment]
your will need jar file from 

https://github.com/tahseen/amazon-cloudsearch-client-java/releases

**Comment by arvinthdd** [comment]
Thanks. Appreciate your work. I thought there could be a maven dependency to pull your jar. Will use the above 'releases' link to download the jar.
