### ISSUE TITLE
Batch limits

### ISSUE THREAD

**Issue by smillerk2** [tahseen/amazon-cloudsearch-client-java#6]
Is there any plan to handle document add requests that would surpass the 5Mb batch upload limit or single document size? http://docs.aws.amazon.com/cloudsearch/latest/developerguide/limits.html

**Comment by tahseen** [comment]
Probably best way to get an answer to post your question here https://forums.aws.amazon.com/forum.jspa?forumID=137

**Comment by smillerk2** [comment]
Sorry, to be clear, it would be great if your library could internally deal with issuing multiple batch requests if the serialized content exceeds the AWS limit. Currently, I could add thousands of large items to your list and this would fail when received by AWS.

**Comment by tahseen** [comment]
Ah I see. I will reopen the issue.

I am not sure yet how to efficiently implement this at the moment.

**Comment by smillerk2** [comment]
Thanks for looking into it. My Java skills are non existent but here is an interesting concept that was done in .NET : https://github.com/martin-magakian/Amazing-Cloud-Search/blob/master/AmazingCloudSearch/CloudSearch.cs
