### ISSUE TITLE
AmazonCloudSearchQuery setReturnFields method contains invalid strings

### ISSUE THREAD

**Issue by rafagan** [tahseen/amazon-cloudsearch-client-java#7]
Its concat '[' and ']' in the search fields, and it makes the query fail

Class: aws.services.cloudsearchv2.search.AmazonCloudSearchQuery
Method: public void setReturnFields(String ... returnFields)
Line: 303 and 310

Code which worked for me:

```
public void setReturnFields(String ... returnFields) {
    StringBuilder builder = new StringBuilder();
    //builder.append("[");
    for (int i = 0; i < returnFields.length; i++) {
        builder.append(returnFields[i]);
        if (i != returnFields.length - 1) {
            builder.append(",");
        }
    }
    //builder.append("]");

    this.returnFields = builder.toString();
}
```

**Comment by tahseenarticle** [comment]
This project is no longer maintained. This project was created to fill the gap in the Amazon Aws Java Sdk. Amazon has added missing search features to their sdk. Please use the offical sdk https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-cloudsearch
